---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizzafrontend
  namespace: dotnet
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pizzafrontend
    spec:
      containers:
      - name: pizzafrontend
        image: noelnondoh/pizzafrontend:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:5900
        - name: backendUrl
          value: http://pizzabackend:5902
  selector:
    matchLabels:
      app: pizzafrontend
---
apiVersion: v1
kind: Service
metadata:
  name: pizzafrontend
  namespace: dotnet
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5900
      targetPort: 5900
  selector:
    app: pizzafrontend