---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizzabackend
  namespace: dotnet
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pizzabackend
    spec:
      containers:
      - name: pizzabackend
        image: noelnondoh/pizzabackend:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:5902
  selector:
    matchLabels:
      app: pizzabackend
---
apiVersion: v1
kind: Service
metadata:
  name: pizzabackend
  namespace: dotnet
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5902
      targetPort: 5902
  selector:
    app: pizzabackend